# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "${{ secrets.REVIEWER }}"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "${{ secrets.REVIEWER }}"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "${{ secrets.REVIEWER }}"
